export const Products = [
    {
      id: 1,
      title: "Apple Watch Series 7 GPS, Aluminium Case, Pink",
      price: 599,
      rating: 5,
      image: "/product2.webp",
    },
    {
      id: 2,
      title: "Apple Watch Series 7 GPS, Aluminium Case, Blue",
      price: 699,
      rating: 4,
      image: "/product2.webp",
    },
    {
      id: 3,
      title: "Apple Watch Series 7 GPS, Aluminium Case, Green",
      price: 799,
      rating: 3,
      image: "/product3.webp",
    },
    {
      id: 4,
      title: "Apple Watch Series 7 GPS, Aluminium Case, Red",
      price: 899,
      rating: 2,
      image: "/product4.webp",
    },
    {
      id: 5,
      title: "Apple Watch Series 7 GPS, Aluminium Case, Pink",
      price: 599,
      rating: 5,
      image: "/product2.webp",
    },
    {
      id: 6,
      title: "Apple Watch Series 7 GPS, Aluminium Case, Pink",
      price: 599,
      rating: 5,
      image: "/product2.webp",
    },
    {
      id: 7,
      title: "Apple Watch Series 7 GPS, Aluminium Case, Pink",
      price: 599,
      rating: 5,
      image: "/product2.webp",
    },
    {
      id: 8,
      title: "Apple Watch Series 7 GPS, Aluminium Case, Pink",
      price: 599,
      rating: 5,
      image: "/product2.webp",
    },
  ];